# Generated by Django 3.2.4 on 2021-07-21 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='front',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.CharField(default=datetime.datetime(2021, 7, 21, 10, 44, 52, 707347, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashCard', to='flashapp.deck'),
        ),
    ]
